# Cloned from https://github.com/Azure-Samples/deployment-environments-cicd-tutorial/blob/main/.github/workflows/environment_update.yml
name: Update Environment

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - 'app/**'
  pull_request:
    types: [synchronize]
    paths:
      - 'app/**'

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Get Configuration
    uses: ./.github/workflows/environment_config.yml

  update_env:
    if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
    name: Update ${{ needs.config.outputs.type }} Environment
    runs-on: ubuntu-latest

    needs: config
    environment: ${{ needs.config.outputs.type }}

    env:
      ENVIRONMENT_NAME: ${{ needs.config.outputs.name }}
      ENVIRONMENT_TYPE: ${{ needs.config.outputs.type }}

    steps:
      - uses: actions/checkout@v4

      - name: Install DevCenter CLI Extension
        run: az extension add --name devcenter --upgrade

      - name: Export version
        id: version
        run: |
          echo "version=$(cat version.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name globalazure2025nz

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: globalazure2025nz-crbne5f9a2cufug9.azurecr.io/lob-app:${{ steps.version.outputs.version }}

      - name: Sync Catalog
        run: |
          az devcenter admin project-catalog sync \
              --catalog-name ${{ vars.AZURE_CATALOG }} \
              --project ${{ vars.AZURE_PROJECT }} \
              --resource-group Global-Azure-Bootcamp

      - name: Get Resource Group
        shell: bash {0}
        run: |
          echo "Getting environment ${{ env.ENVIRONMENT_NAME }}..."
          environment_rg=$(az devcenter dev environment show --name ${{ env.ENVIRONMENT_NAME }} \
              --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
              --only-show-errors --query resourceGroupId --output tsv 2>&1)

          if [ $? -ne 0 ]; then
              # Prod (main) environment may not be created yet
              if [[ $environment_rg =~ "EnvironmentCannotBeFound" || $environment_rg =~ "EnvironmentNotFound" ]] && [[ "$ENVIRONMENT_TYPE" == "Prod" ]]; then
                  echo "Environment ${{ env.ENVIRONMENT_NAME }} not found, creating..."

                  environment_rg=$(az devcenter dev environment create \
                      --name ${{ env.ENVIRONMENT_NAME }} --environment-type ${{ env.ENVIRONMENT_TYPE }} \
                      --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
                      --catalog-name ${{ vars.AZURE_CATALOG }} --environment-definition-name ${{ vars.AZURE_CATALOG_ITEM }} \
                      --parameters '{ "name": "${{ env.ENVIRONMENT_NAME }}", "app_version": "${{ steps.version.outputs.version }}", "greeting": "Hello from event ${{ github.event_name }}" }' --only-show-errors
                      --query resourceGroupId --output tsv 2>&1)

                  if [ $? -ne 0 ]; then
                      echo "Failed to create environment ${{ env.ENVIRONMENT_NAME }}"
                      echo "::error::az devcenter dev environment create command failed: $environment_rg"; exit 1
                  fi
              else
                  echo "Failed to get environment ${{ env.ENVIRONMENT_NAME }}"
                  echo "::error::az devcenter dev environment show command failed: $environment_rg"; exit 1
              fi
          fi

          environment_group=${environment_rg##*/}
          environment_sub=${environment_rg%/resourceGroups*}
          environment_sub=${environment_sub##*/}

          echo "ENVIRONMENT_GROUP=$environment_group" >> $GITHUB_ENV
          echo "ENVIRONMENT_SUB=$environment_sub" >> $GITHUB_ENV

          echo "- [View environment resources in the Azure portal](https://portal.azure.com/#@${{ vars.AZURE_TENANT_ID }}/resource$environment_rg)" >> $GITHUB_STEP_SUMMARY
